version: "2"
services:
  python-service:
    build: ./python
    volumes: 
      - ./python:/usr/src/app
    ports:
      - "5050:80"
    
  php-service:
    image: php:apache
    volumes:
      - ./php:/var/www/html
    ports:
      - "5051:80"
#    depends_on: 
#      - python-service
  
