version: "2"
services:
  python-service:
    build: ./python
    container_name: python-service
    volumes: 
      - ./python:/usr/src/app
    ports:
      - "5050:80"
    
  php-service:
    image: php:apache
    container_name: php-service
    volumes:
      - ./php:/var/www/html
    ports:
      - "5051:80"
